### ISSUE TITLE
Add a reverse IP processor (IP to FQHN)

### ISSUE THREAD

**Issue by mathieu-rossignol** [Hurence/logisland#193]
In a security context or web analytics, it could be useful to have a reverse ip processor ? (IP to FQHN. i.e: 191.27.203.8 -> www.xyzindustries.com) or should the reverse ip feature be an option for the geoip processor (that is not only getting the GPS coords but also the FQHN matching the IP address)
Guidelines for implementation: http://www.tcpipguide.com/free/t_DNSReverseNameResolutionUsingtheINADDRARPADomain-2.htm

Already mentioned here https://github.com/Hurence/logisland/issues/14 but as an option for geoip processor. Think it's better as a standalone one, is'nt it ?

**Comment by MiniPlayer** [comment]
Sometimes no domain name match an ip. (It is not present in the in-addr.arpa domain).
For example 1.2.4.6 does not match but 

We can still found owner of domain/ip => with 'whois' command for example. 1.2.4.6 -> 
inetnum:        1.2.4.0 - 1.2.4.255
netname:        CNNIC-CRITICAL-CN
descr:          China Network Information Center
descr:          No.4, Zhongguancun No.4 South Street,
descr:          Haidian District, Beijing
descr:          P.O.Box: No.6 Branch-box of No.349 Mailbox, Beijing
country:        CN
address:        Beijing, China

I guess it happens when the domain is owned but not used at the moment.

So a processor finding information of type whois should be a good thing as well I think.

**Comment by mathieu-rossignol** [comment]
Think this one has got a first good implementation. I just fixed a bug on this one with https://github.com/Hurence/logisland/commit/685c1c2282be291358f28cb017a3a513808768ee but I have now used it enough to fill confident with it. Shall we close this issue ?

**Comment by mathieu-rossignol** [comment]
Done
